[project]
name = "privacy-enabled-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.5"
dependencies = [
    "fastapi[standard]==0.116.1",
    "langchain-openai==0.3.27",
    "langchain==0.3.26",
    "langgraph==0.5.2",
    "python-dotenv==1.1.1",
    "langfuse==3.2.1",
    "truststore==0.10.1",
    "pydantic==2.11.7",
    "langchain-community==0.3.27",
    "pydantic-extra-types==2.10.5",
    "phonenumbers==9.0.9",
    "valkey==6.1.0",
    "faker==37.4.0",
    "cryptography==45.0.5",
    "langgraph-checkpoint-redis==0.0.8",
    "duckduckgo-search==8.1.1",
    "stamina==25.1.0",
]

[dependency-groups]
dev = [
    "jupyter==1.1.1",
    "pre-commit==4.2.0",
    "pytest==8.4.1",
    "pytest-asyncio==1.0.0",
    "ruff==0.12.3",
    "ty==0.0.1a14",
]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
